return {
    ["neo-tree"] = true,
    ["nvim-web-devicons"] = true,
    ["which-key"] = true,
    aerial = true,
    bufferline = true,
    cmp = true,
    dashboard = true,
    highlighturl = true,
    indent_blankline = true,
    notify = true,
    rainbow = true,
    symbols_outline = true,
    telescope = true,
    treesitter = true,
    ["nvim-tree"] = false,
    hop = false,
    beacon = false,
    lightspeed = false,
    vimwiki = false,
}
