---@type LazySpec
return vim.tbl_map(function(plugin) return { plugin, enabled = vim.g.vscode } end, {
    "neovim/nvim-lspconfig",
    "williamboman/mason-lspconfig.nvim",
    "folke/todo-comments.nvim",
    "max397574/better-escape.nvim",
    "hrsh7th/nvim-cmp",
    "Exafunction/codeium.vim",
    "mfussenegger/nvim-dap",
    "linrongbin16/gitlinker.nvim",
    "cbochs/grapple.nvim",
    "rebelot/heirline.nvim",
    "m-demare/hlargs.nvim",
    "lukas-reineke/indent-blankline.nvim",
    "L3MON4D3/LuaSnip",
    "chentoast/marks.nvim",
    "jay-babu/mason-null-ls.nvim",
    "jay-babu/mason-nvim-dap.nvim",
    "nvim-neotest/neotest",
    "folke/noice.nvim",
    "nvim-treesitter/nvim-treesitter",
    "folke/trouble.nvim",
    "kevinhwang91/nvim-ufo",
    "gbprod/yanky.nvim",
})
